### ISSUE TITLE
Hämta latitud och longitud från varje student vi får ut från student json ESTIMATE: 5h

### ISSUE THREAD

**Issue by js223kz** [Visualisering/Visualisering-backend#13]
- [ ] Testa att open street map levererar tillbaka latitud och longitud för varje student vi skickat in.
- [ ] Konstruera ett objekt med lat-long för varje student-stad
- [ ] Konstruera json som skickas med websockets till klienten

**Comment by Angamanga** [comment]
Det verkar gå att använda Nomenatim och hämta ut latitud och longitud, http://wiki.openstreetmap.org/wiki/Nominatim.
