### ISSUE TITLE
Bestäm en struktur för det som ska levereras till front-end ESTIMATE: 0.5 h

### ISSUE THREAD

**Issue by Angamanga** [Visualisering/Visualisering-backend#16]

**Comment by rpkarlsson** [comment]
När jag gjorde sfären så tänkte jag mig ett json-objekt som set ut ungefär som:
https://github.com/Visualisering/Visualisering-frontend/blob/master/src/index.js#L6

Tänker mig att time är i formatet https://en.wikipedia.org/wiki/Unix_time så borde det bli väldigt lättarbetat i komponenten sen.

**Comment by Angamanga** [comment]
@rk222ev Ja, det går ju absolut att fixa. Vad tror du om att lägga in koden/slackmeddelanden/annat som ska rulla pa skärmen/ i samma objekt eller bör det vara uppdelat? Har för mig att vi pratade om att använda samma objekt för både koordinater och innehållet vid något tillfälle?

**Comment by rpkarlsson** [comment]
Någonstans hade jag tänkt mig att försöka hålla klienten så "dum" som möjligt och få så förberedd data som möjligt. Men @mw222rs, du har ju kikat lite mer på redux och har, om jag förstått saken rätt, tänkt mer i banan att skicka all data i ett objekt och sen fixa till den till varje react komponent direkt på klienten?

**Comment by Angamanga** [comment]
Websocketsarna funkar nu (alldeles strax ska bara gora testa klart och pusha/pr) kan skicka data i det format som du beskriver @rk222ev. Vore lite spännande att prova att fa ihop den biten ivarjefall?
