### ISSUE TITLE
Strukturen på filer

### ISSUE THREAD

**Issue by Angamanga** [Visualisering/Visualisering-backend#2]

**Comment by rpkarlsson** [comment]
Uppdatera gärna https://github.com/Visualisering/Visualisering/wiki/Mjukvaruarkitektur#backend om filstrukturen rör sig i en annan riktning än den som är dokumenterad.

**Comment by Angamanga** [comment]
@rk222ev Jag har börjat ändra på filstrukturen i dokumentet men jag blev osäker på hur detaljerad jag ska vara. Blev lite fundersam på vilka bibliotek som ska vara med också. Bör vi lägga in alla npm-moduler vi lägger till eller räcker det med node.js?

**Comment by rpkarlsson** [comment]
Tänker mig väldigt övergripande. Inga direkta detaljer utan bara det generella tankesättet som bör förmedlas i min mening.

Tycker det räcker med NPM. Tanken är att bara ta upp arkitekturellt signifikanta bibliotek.

**Comment by Angamanga** [comment]
Ok, jag da ar det klart for now tycker jag. Har bara lagt till mapparna i backend-strukturen, tycker det racker sa for filerna kommer andras under arbetets gang.

**Comment by rpkarlsson** [comment]
:+1: 
Ja, dokumentet är ju levande så behöver arkitekturen justerar är ju inte det ett problem.
