### ISSUE TITLE
Implement functionality for scheduled event getUsers from Api ESTIMATE 3h

### ISSUE THREAD

**Issue by js223kz** [Visualisering/Visualisering-backend#33]

**Comment by fyrkant** [comment]
I've been thinking about this and maybe it would be easier to save the cached users to a file and mark that file with the date and time of when it was retrieved. Then on each read of that file one could have a simple if-else that checks if the data is older than X days we ask the API for new data, else we read directly form the file. That would remove the overhead of having a scheduled event always running on the server.

**Comment by js223kz** [comment]
Lets discuss it tomorrow at morning meeting. I personally have little knowledge of overhead cost when it comes to code. The idea was to update the file once a month instead of checking file last modified date each time.

**Comment by fyrkant** [comment]
Only meetings on Monday, Wednesday and Friday, right? Or did we say something else during today's meeting?

If we think about it like this: what functionality is it that we want? 

We want to - _when the data is requested_ - make sure that the data is not older than a month (or any arbitrary time span) and fetch new data if it is. We don't really have to make sure that the cache is ALWAYS fresh, if no one is requesting the data - like during the summer break or something like that - old data can be left as is. 

A scheduled event seems over-complicated to me, I'd go with the simpler on-read check. The fewer moving parts the better!

**Comment by js223kz** [comment]
Morning meetings every day at 10 from now on since we're getting closer to deadline. It's three lines of code so it's easy to change either way. But as you said last meeting, let's  just get the flow going and then we can poke around in details.

**Comment by js223kz** [comment]
Not necessary closing issue
