### ISSUE TITLE
Implement redux on server ESTIMATE: 8 h

### ISSUE THREAD

**Issue by Angamanga** [Visualisering/Visualisering-backend#39]

**Comment by rpkarlsson** [comment]
Once again. Played around with node during the weekend.
https://github.com/rk222ev/Visualisering-backend
Is a working node app with redux and some basic services. Showcases how it could be tied together.

**Comment by Angamanga** [comment]
Great!

**Comment by Angamanga** [comment]
Closed by pull request #45.
