### ISSUE TITLE
Exchange express to simpler routing library ESTIMATE:1h

### ISSUE THREAD

**Issue by Angamanga** [Visualisering/Visualisering-backend#41]

**Comment by rpkarlsson** [comment]
Played with node during the weekend. This could be a possible solution to move forward with.
It only uses the already included http module. Thought I'd share.

https://github.com/rk222ev/Visualisering-backend/blob/redux/src/lib/http-server.js

**Comment by js223kz** [comment]
closed by pullrequest #45
