### ISSUE TITLE
Data to send to Matrix-module ESTIMATE: 10 h

### ISSUE THREAD

**Issue by sk222sw** [Visualisering/Visualisering-backend#42]
Ordered list of the data I'd like to use in the Matrix module: 
1. Source code
2. Repository name
3. File name 
4. Repo owner (github username)
5. File contributors (github usernames)

**Comment by Angamanga** [comment]
Since we are getting this data from a commit instead of a file, is it ok for you to exchange File contributors to Commiter instead?

**Comment by sk222sw** [comment]
Does that mean you will provide the code for a commit instead of the file? If so, that's perfectly fine, but we will probably need several commits, or the visualization might become repetitive and boring.

If not, and you're providing the code from a file, showing a commiter seems a bit pointless, since the idea of showing contributors is to give credit to everyone who contributed, not who did the commit that you got your information from. But if you can't extract contributors from the commit info that's ok, it's not really necessary :)
