### ISSUE TITLE
Implement redux/service/data-processor example for discussion ESTIMATE 5h

### ISSUE THREAD

**Issue by rpkarlsson** [Visualisering/Visualisering-backend#44]
Talking about it is hard so I thought I would show what I keep talking about.

So using a fork I liked from Annas repo I forced Mattias to help me setup an example on how we could organize things and also some working examples demonstrating an easy way to collect, process and deliver the data using the architecture we have previously discussed during inception and elaboration. The same architecture that our documentation depicts.
The implementation is crude but i threw it together during a few hours so please bear that in mind.

See: https://github.com/rk222ev/Visualisering-backend

Folder structure:

``` shell
.
├── datasets   # Intended to contain static saves of our different data to seed at startup
└── src
    ├── data-processors # Contains a module responsible for one level of our state tree
    ├── services        # Contains modules for each of our different external and internal services 
    └── store           # Contains files for our redux data store
```

This would allow the frontend to be free from data processing and it becomes extremely easy to handle the data. Since we process data on the backend anyway this feels, to me at least, like the optimal solution.

If anyone feels that the redux pattern is intimidating there's really no need for everyone to work with that part. Connecting data processors with the state-tree is fairly straightforward and the bulk of the work is to make the different services and processors. This could include caching, error handling, general testing and so forth. 

This quick demo contains a githubservice capable of collecting recent commit from the frontend repository, a fake student service connecting the commit to a students geolocation. And a data processor connecting the two producing the sphere components data.
The result loooks like this:

``` shell
{   commits:
   [ { lng: '16.356824', lat: '56.665954', time: 1456595668000 },
     { lng: '16.356824', lat: '56.665954', time: 1456595206000 },
     { lng: '16.356824', lat: '56.665954', time: 1456525298000 },
     { lng: '16.356824', lat: '56.665954', time: 1456524429000 },
     { lng: '16.356824', lat: '56.665954', time: 1456516688000 },
     { lng: '16.356824', lat: '56.665954', time: 1456516535000 },
     { lng: '16.356824', lat: '56.665954', time: 1456502265000 },
     { lng: '16.356824', lat: '56.665954', time: 1456502132000 },
     { lng: '16.356824', lat: '56.665954', time: 1456502132000 },
     { lng: '16.356824', lat: '56.665954', time: 1456502132000 },
     { lng: '16.356824', lat: '56.665954', time: 1456502011000 },
     { lng: '16.356824', lat: '56.665954', time: 1456502011000 },
     { lng: '16.356824', lat: '56.665954', time: 1456502011000 },
     { lng: '16.356824', lat: '56.665954', time: 1456502011000 },
     { lng: '16.356824', lat: '56.665954', time: 1456484505000 },
     { lng: '16.356824', lat: '56.665954', time: 1456481543000 },
     { lng: '16.356824', lat: '56.665954', time: 1456480692000 },
     { lng: '16.356824', lat: '56.665954', time: 1456142877000 },
     { lng: '16.356824', lat: '56.665954', time: 1456091008000 },
     { lng: '16.356824', lat: '56.665954', time: 1456060999000 },
     { lng: '16.356824', lat: '56.665954', time: 1456060882000 },
     { lng: '16.356824', lat: '56.665954', time: 1456052317000 },
     { lng: '16.356824', lat: '56.665954', time: 1456051789000 },
     { lng: '16.356824', lat: '56.665954', time: 1456051584000 },
     { lng: '16.356824', lat: '56.665954', time: 1456051331000 },
     { lng: '16.356824', lat: '56.665954', time: 1456051331000 },
     { lng: '16.356824', lat: '56.665954', time: 1455866319000 },
     { lng: '16.356824', lat: '56.665954', time: 1455842894000 },
     { lng: '16.356824', lat: '56.665954', time: 1455842732000 },
     { lng: '16.356824', lat: '56.665954', time: 1455842232000 } ] }

```

Each object in the commits array consists of a students coordinates from the provided student example file and the timestamp for when the commit was done to the frontend repo.

On any state changes the tree is pushed out to the websockets.
Clients could also potentially request a subset of the tree. But that would be a future implementation.

This is my proposal how to solve our problem.

**Comment by fyrkant** [comment]
Hah, there really wasn't any force connected to me helping out! I think everyone knows I like (love!) redux and I think that this looks like a great solution. Small, sleek and functional. Easy to understand and easy to expand. 

So, now we have a functioning backend and two weeks of construction left - let's start rocking for real! :metal:
