### ISSUE TITLE
Koppla repo till travis

### ISSUE THREAD

**Issue by Angamanga** [Visualisering/Visualisering-backend#5]

**Comment by fyrkant** [comment]
Måste fixa till npm test-skriptet, det är det som travis kör för att få igenom builden.

**Comment by js223kz** [comment]
Aha ok jag trodde vi körde på olika eftersom det är olika repo. Sorry
Den 28 jan 2016 17:59 skrev "Mattias" notifications@github.com:

**Comment by fyrkant** [comment]
Nej jag menar alltså i det här repot, I package.json måste test-skriptet ändras så att mocha körs.

**Comment by Angamanga** [comment]
closes #5
