### ISSUE TITLE
Send data to sphere module ESTIMATE 10h

### ISSUE THREAD

**Issue by js223kz** [Visualisering/Visualisering-backend#56]

**Comment by rpkarlsson** [comment]
Earth and sphere already has its data or am I missing something? On startup we have one action collecting the latest commits from repos (a repo right now, should be expanded to several) and then when a commit is done the webhook listener add new ones (overwrites at the moment, should add).

Am I missing or misunderstanding something?

**Comment by js223kz** [comment]
No you're not missing anything. But realized there wasn't a specific issue
for this and to report my hours in a correct way I opened it. Will close it
as soon as everybody reported their time. Realized I should have wrote an
explanation as a comment.
Den 7 mar 2016 8:34 AM skrev "Robin Karlsson" notifications@github.com:

**Comment by rpkarlsson** [comment]
Ah ok. Good.  Then nevermind me.
Just checking so were on the same page.
