### ISSUE TITLE
Connect github webhhook ESTIMATE 15h

### ISSUE THREAD

**Issue by js223kz** [Visualisering/Visualisering-backend#58]

**Comment by rpkarlsson** [comment]
Isn't this one in place? We only need to reapply the reducer and connection to redux once we've added the functionality to read code from the commit (as opposed to from the file on the server).

Once again, am I missing or misunderstanding something?

**Comment by js223kz** [comment]
Same answer here. Opened it to report worked hours. Should have wrote it as
a comment.
Den 7 mar 2016 8:36 AM skrev "Robin Karlsson" notifications@github.com:

**Comment by rpkarlsson** [comment]
Great. And again just checking as I was a bit confused. 

Ignore me.
