### ISSUE TITLE
Matrix "code" field problem

### ISSUE THREAD

**Issue by sk222sw** [Visualisering/Visualisering-backend#63]
I'm get this when decoding "code" from the matrix data objects. Are you sure you get/send the correct data?

`const WebSocketServer = require("ws").Server;
const httpServer = require("./src/lib/http-server");
const actions = require("./src/store/actions");
const store = require("./src/store/store");
const sphere = require("./src/data-processors/sphere");

const server = httpServer.init();
const wss = new WebSocketServer({server});

// Hookup datastore and processors
sphere.dataSet()
  .then(commits => store.dispatch(actions.addLatestCommits(commits)));

store.subscribe(
  () => {
    if (store.getState()) {
      const data = store.getState();
      const action = JSON.stringify({type: "BACKEND_DATA", data});

```
  console.log(data);

  wss.broadcast(action);
}
```

  }
);

wss.broadcast = data => wss.clients.forEach(client => client.send(data));

wss.on("connection", ws => {
  const action = JSON.stringify({type: "WS_CONNECTED"});
  ws.send(action);

  ws.on("message", message => {
    try { // Using a try-catch because JSON.parse explodes on invlaid JSON.
      const action = JSON.parse(message);
      console.log("Received action from client:");
      console.log(action);
      store.dispatch(action);
    } catch (e) {
      console.error(e.message);
      ws.send("Unable to parse JSON string.");
    }
  });
});
`

**Comment by Angamanga** [comment]
Its the code from the file "app.js" that we use as default-code until we get hold of the proper code for each commit... is it enough? Otherwise we can change to another file that has more code...

**Comment by sk222sw** [comment]
Oh, so this is a sample and not an error? If so it should be enough for now

**Comment by Angamanga** [comment]
Yes its a sample :)
